[modengine]
debug = false
external_dlls = []

[extension.mod_loader]
enabled = true
loose_params = false

mods = [
    { enabled = true, name = "default", path = "..\\MergedMods" }
]

[extension.scylla_hide]
enabled = false