name: .Net Publish
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    name: "Build"
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x' # SDK Version to use;
        
      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish '${{ runner.workspace }}/ERModsMerger/ERModsMerger/ERModsMerger.csproj' -p:PublishProfile=FolderProfile

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'ERModsMerger-${{  github.ref_name }}'
          path: '${{ runner.workspace }}/ERModsMerger/ERModsMerger/bin/Publish'
      - name: Draft Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: '${{ runner.workspace }}/ERModsMerger/ERModsMerger/bin/Publish/ERModsMerger-${{  github.ref_name }}.zip'
